version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - mvn clean package
  post_build:
    commands:
      - aws s3 cp target/createJob-0.0.1-SNAPSHOT.jar s3://spring-boot-bucket5/springbuild/ 
      # - aws s3 cp target/*.jar s3://spring-boot-bucket5/springbuild/target/createJob-0.0.1-SNAPSHOT.jar
artifacts:
  files:
    - target/*.jars
